<a href="https://colab.research.google.com/github/aasjunior/UdemyEstruturaDados_Python/blob/main/Matrizes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Matrizes

Lista mais perfomatica do que utilizar dicionários.

In [1]:
import numpy as np

In [2]:
matriz = np.array([[2,3,1],[4,5,7]])

In [3]:
matriz

array([[2, 3, 1],
       [4, 5, 7]])

Retornar formato da coluna (2 linhas por 3 colunas)

In [7]:
matriz.shape

(2, 3)

Retornar valores por linha

In [8]:
matriz[0]

array([2, 3, 1])

Retornar valores por coluna

In [10]:
matriz[0][2]

1

In [11]:
matriz[1][0]

4

Percorrer todos os elementos

In [12]:
for i in range(matriz.shape[0]):
  print(matriz[i])
  for j in range(matriz.shape[1]):
    print(matriz[i][j])

[2 3 1]
2
3
1
[4 5 7]
4
5
7
