<a href="https://colab.research.google.com/github/aasjunior/UdemyEstruturaDados_Python/blob/main/04_pilhas_filas_deques/Filas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Filas



*   FIFO (First In First Out): Primeiro a entrar, primeiro a sair
*   Aplicações
    * Modelar aviões aguardando decolar
    * Pacotes de dados esperando serem transmitidos pela rede
    * Fila da impressora
    



### Operações


*   Enfileirar
    * Colocar um item no final da fila

*   Desenfileirar
    * Remover um item do início da fila

*   Vizualizar o início da fila
    * Mostra o elemento que está no início da fila



### Fila Circular
*   Uma fila circular é uma variação da estrutura de dados de fila que trata o buffer de armazenamento como se fosse circular, em vez de linear.

*   Permite um melhor aproveitamento do espaço de armazenamento, pois o espaço vazio pode ser reutilizado imediatamente.

* Pode ser implementada usando um array com dois ponteiros, um para o início da fila e outro para o final da fila.

* Quando um elemento é adicionado à fila, o ponteiro do final é incrementado e o elemento é armazenado na posição correspondente do array.

* Quando um elemento é removido da fila, o ponteiro do início é incrementado e o elemento é removido da posição correspondente do array.

* Se um dos ponteiros atingir o final do array, ele é ajustado para apontar para o início do array novamente.

* Big-O: O(1) Constante

### Implementação

In [ ]:
import numpy as np

In [ ]:
class FilaCircular:
  def __init__(self, capacidade):
    self.capacidade = capacidade
    self.inicio = 0
    self.final = -1
    self.numero_elementos = 0
    self.valores = np.empty(self.capacidade, dtype=int)

  def __fila_vazia(self):
    return self.numero_elementos == 0

  def __fila_cheia(self):
    return self.numero_elementos == self.capacidade

  def enfileirar(self, valor):
    if self.__fila_cheia():
      print('A fila está cheia')
      return

    if self.final == self.capacidade -1:
      self.final = -1

    self.final += 1
    self.valores[self.final] = valor
    self.numero_elementos +=1

  def desenfileirar(self):
    if self.__fila_vazia():
      print('A fila já está vazia')
      return

    temp = self.valores[self.inicio]
    self.inicio += 1

    if self.inicio == self.capacidade - 1:
      self.inicio = 0

    self.numero_elementos -= 1
    return temp

  def primeiro(self):
    if self.__fila_vazia():
      return -1
    return self.valores[self.inicio]

In [ ]:
fila = FilaCircular(5)

In [ ]:
fila.primeiro()

-1

In [ ]:
# 1
fila.enfileirar(1)
fila.primeiro()

1

In [ ]:
fila.enfileirar(3)
fila.enfileirar(4)
fila.enfileirar(5)

In [ ]:
fila.enfileirar(6)

In [ ]:
fila.enfileirar(2)

A fila está cheia


In [ ]:
fila.desenfileirar()
fila.desenfileirar()

3

In [ ]:
fila.primeiro()

4

In [ ]:
fila.valores

array([1, 3, 4, 5, 6])

In [ ]:
# retorna indices correspondentes aos valores do inicio e do final da fila
fila.inicio, fila.final

(2, 4)

In [ ]:
fila.valores[fila.final]

6

In [ ]:
fila.valores[fila.inicio]

4

### Fila de Prioridade



*   Os itens são ordenados por valor-chave, de modo que o item com a chave mais baixa ou alta esteja sempre na frente

*   Elementos de alta prioridade são colocados no início da fila, de média rpioridade no meio da fila, e de baixa no final da fila




#### Implementação

In [1]:
import numpy as np

In [35]:
class FilaPrioridade:
  def __init__(self, capacidade):
    self.capacidade = capacidade
    self.numero_elementos = 0
    self.valores = np.empty(self.capacidade, dtype=int)

  def __fila_vazia(self):
    return self.numero_elementos == 0

  def __fila_cheia(self):
    return self.numero_elementos == self.capacidade

  def enfileirar(self, valor):
    if self.__fila_cheia():
      print('A fila está cheia')
      return

    if self.numero_elementos == 0:
      self.valores[self.numero_elementos] = valor
      self.numero_elementos += 1
    else:
      x = self.numero_elementos - 1
      while x >= 0:
        if valor > self.valores[x]:
          self.valores[x + 1] = self.valores[x]
        else:
          break
        x -= 1

      self.valores[x + 1] = valor
      self.numero_elementos += 1

  def desenfileirar(self):
    if self.__fila_vazia():
      print('A fila está vazia')
      return

    valor = self.valores[self.numero_elementos - 1]
    self.numero_elementos -= 1
    return valor


  def primeiro(self):
    if self.__fila_vazia():
      return -1
    return self.valores[self.numero_elementos - 1]

In [48]:
fila = FilaPrioridade(5)

In [49]:
fila.primeiro()

-1

In [50]:
# 30
fila.enfileirar(30)
fila.primeiro()

30

In [51]:
# 50 30
fila.enfileirar(50)
fila.primeiro()

30

In [52]:
# Tradicional: 10 50 30
# Prioridade: 50 30 10
fila.enfileirar(10)
fila.primeiro()

10

In [53]:
fila.valores

array([50, 30, 10,  0, 48])

In [54]:
# Tradicional: 40 10 50 30
# Prioridade: 50 40 30 10
fila.enfileirar(40)
fila.primeiro()

10

In [55]:
fila.valores

array([50, 40, 30, 10, 48])

In [56]:
# Tradicional: 20 40 10 50 30
# Prioridade: 50 40 30 20 10
fila.enfileirar(20)
fila.primeiro()

10

In [57]:
fila.valores

array([50, 40, 30, 20, 10])

In [58]:
fila.enfileirar(2)

A fila está cheia


In [59]:
fila.desenfileirar()
fila.primeiro()

20

In [60]:
fila.desenfileirar()
fila.primeiro()

30

In [61]:
fila.desenfileirar()
fila.primeiro()

40

In [62]:
fila.valores

array([50, 40, 30, 20, 10])

In [63]:
fila.enfileirar(5)
fila.primeiro()

5

In [64]:
fila.valores

array([50, 40,  5, 20, 10])